In [ ]:
import torch

In [ ]:
x = [12,23,34,45,56,67,78]
torch.is_tensor (x)
torch.is_storage(x)

False

In [ ]:
y = torch.randn(1,2,3,4,5)
torch.is_tensor(y)

True

In [ ]:
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [ ]:
import numpy as np
x1 = np.array(x)
x1

array([12, 23, 34, 45, 56, 67, 78])

In [ ]:
torch.from_numpy(x1)

tensor([12, 23, 34, 45, 56, 67, 78])

In [ ]:
torch.rand(10)

tensor([0.8673, 0.3980, 0.4160, 0.6725, 0.6685, 0.7467, 0.8639, 0.3296, 0.3190,
        0.9704])

In [ ]:
import torch
a=torch.randn(4,4)
print (a)
torch.chunk (a,2)

tensor([[-0.3904,  0.7299, -0.1953,  2.4616],
        [-1.2678,  0.9503, -1.3486, -0.6307],
        [ 0.9139,  0.7985,  0.6433, -0.6937],
        [-0.4608, -0.3269,  1.0483,  0.1733]])


(tensor([[-0.3904,  0.7299, -0.1953,  2.4616],
         [-1.2678,  0.9503, -1.3486, -0.6307]]),
 tensor([[ 0.9139,  0.7985,  0.6433, -0.6937],
         [-0.4608, -0.3269,  1.0483,  0.1733]]))

In [1]:
import torch
torch.manual_seed(1234)

In [2]:
torch.manual_seed(1234)
torch.randn(4,4)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817],
        [ 0.0539,  0.6684, -0.0597, -0.4675],
        [-0.2153,  0.8840, -0.7584, -0.3689],
        [-0.3424, -1.4020,  0.3206, -1.0219]])

In [3]:
torch.Tensor(4,4).uniform_(0,1)

tensor([[0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294],
        [0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343]])